name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: "2.0.2"
      - name: Get Flutter Package
        run: flutter pub get
        working-directory: ./flutter_app

      - name: Run Flutter Test
        run: flutter test --coverage --coverage-path=~/coverage/lcov.info
        working-directory: ./flutter_app

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
